---
title: "Sampling Distribution and Sample Mean and Sample Standard Deviation"
titleshort: "Sampling Distribution and Sample Mean and Sample Standard Deviation"
description: |
  Sample mean and sample standard deviations, suppose we know the population mean and population standard deviations.
date: 2021-03-10
date_start: 2021-03-10
output:
  pdf_document:
    pandoc_args: '../../_output_kniti_pdf.yaml'
    includes:
      in_header: '../../preamble.tex'
  html_document:
    pandoc_args: '../../_output_kniti_html.yaml'
    includes:
      in_header: "../../hdga.html"
always_allow_html: true
urlcolor: blue
---

### Sample Mean and Sample Standard Deviations given Population Mean and Standard Deviations

```{r global_options, include = FALSE}
try(source("../../.Rprofile"))
```

`r text_shared_preamble_one`
`r text_shared_preamble_two`
`r text_shared_preamble_thr`

#### Sample Mean given Population Mean and Standard Deviation

We know the population mean, and we know the population standard deviation. Suppose we even know that the underlying data follows the normal distribution. For example, imagine given income, price, preference and shocks, there is a distribution of height outcomes. Given shared preferences, the distribution comes from observed (income, price) as well as unobserved (shocks) heterogeneities. Within a village, however, we do not have a large enough of new-borne every year, the "sample" of people been borne is in effect randomly drawn from the underlying population of potential children.

Given $M$ children that we observe, we can compute the sample mean and the sample standard deviation. What is the distribution of the sample mean and the sample standard deviation? In another word, if income, price, preference and shocks distributions are the same across ten thousand villages, where is the distribution of village-level observed mean height at two years of age as well as the standard deviation of height at two years of age.

For the sample mean, each data-point that jointly generate the sample mean is from the normal distribution with known mean and known standard deviation.

$$
E
$$
