---
title: "R String Arrays"
titleshort: "String Operations"
description: |
  Split, concatenate, subset strings
core:
  - package: r
    code: |
      paste0()
      sub()
      gsub()
      grepl()
      sprintf()
      tail()
      strsplit()
      basename()
      dirname()
date: 2020-04-11
output:
  pdf_document:
    pandoc_args: '../../_output_kniti_pdf.yaml'
    includes:
      in_header: '../../preamble.tex'
  html_document:
    pandoc_args: '../../_output_kniti_html.yaml'
    includes:
      in_header: "../../hdga.html"
always_allow_html: true
urlcolor: blue
---

### String Arrays

```{r global_options, include = FALSE}
try(source("../../.Rprofile"))
```

`r text_shared_preamble_one`
`r text_shared_preamble_two`
`r text_shared_preamble_thr`

#### String Replace

```{r, amto.array.fs_ary_string.replace, eval=FALSE}
# String replacement
gsub(x = paste0(unique(df.slds.stats.perc$it.inner.counter), ':',
                unique(df.slds.stats.perc$z_n_a_n), collapse = ';'),
     pattern = "\n",
     replacement = "")
gsub(x = var,  pattern = "\n", replacement = "")
gsub(x = var.input,  pattern = "\\.", replacement = "_")
```

##### String Contains

- r if string contains

```{r support dtype string if contains}
st_example_a <- 'C:/Users/fan/R4Econ/amto/tibble/fs_tib_basics.Rmd'
st_example_b <- 'C:/Users/fan/R4Econ/amto/tibble/_main.html'
grepl('_main', st_example_a)
grepl('_main', st_example_b)
```

#### String Concatenate

```{r amto.array.fs_ary_string.concatenate}
# Simple Collapse
vars.group.by <- c('abc', 'efg')
paste0(vars.group.by, collapse='|')
```

#### String Add Leading Zero

```{r amto.array.fs_ary_string.leadingzero}
# Add Leading zero for integer values to allow for sorting when
# integers are combined into strings
it_z_n <- 1
it_a_n <- 192
print(sprintf("%02d", it_z_n))
print(sprintf("%04d", it_a_n))
```

#### Substring and File Name

From path, get file name without suffix.

- r string split
- [r list last element](https://stackoverflow.com/a/83222/8280804)
- [r get file name from path](https://stackoverflow.com/a/29114007/8280804)
- [r get file path no name](https://stackoverflow.com/a/47189541/8280804)

```{r}
st_example <- 'C:/Users/fan/R4Econ/amto/tibble/fs_tib_basics.Rmd'
st_file_wth_suffix <- tail(strsplit(st_example, "/")[[1]],n=1)
st_file_wno_suffix <- sub('\\.Rmd$', '', basename(st_example))
st_fullpath_nosufx <- sub('\\.Rmd$', '', st_example)
st_lastpath_noname <- (dirname(st_example))
st_fullpath_noname <- dirname(st_example)

print(strsplit(st_example, "/"))
print(st_file_wth_suffix)
print(st_file_wno_suffix)
print(st_fullpath_nosufx)
print(st_lastpath_noname)
print(st_fullpath_noname)
```
