## ----global_options, include = FALSE-------------------------------------------------------------------
try(source("../../.Rprofile"))


## ------------------------------------------------------------------------------------------------------
# Compose together a path 
print(paste0('.Platform$file.sep=', .Platform$file.sep))
spn_file_path = file.path("C:", "Users", "fan", "R4Econ", "amto", "tibble", 
                          "fs_tib_basics.Rmd", 
                          fsep = .Platform$file.sep)
# print
print(spn_file_path)


## ------------------------------------------------------------------------------------------------------
st_example <- 'C:/Users/fan/R4Econ/amto/tibble/fs_tib_basics.Rmd'
st_file_wth_suffix_s <- tail(strsplit(st_example, "/")[[1]],n=1)
st_file_wno_suffix_s <- tools::file_path_sans_ext(basename(st_example))
st_fullpath_nosufx_s <- sub('\\.Rmd$', '', st_example)
st_fullpath_noname_s <- dirname(st_example)

print(paste0('st_file_wth_suffix_s:', st_file_wth_suffix_s))
print(paste0('st_file_wno_suffix_s:', st_file_wno_suffix_s))
print(paste0('st_fullpath_nosufx_s:', st_fullpath_nosufx_s))
print(paste0('st_fullpath_noname_s:', st_fullpath_noname_s))


## ------------------------------------------------------------------------------------------------------
# Compose together a path 
spn_example <- 'C:/Users/fan/R4Econ/amto/tibble/fs_tib_basics.Rmd'
# Replace default system slash, assume spn was generated by system. 
ls_srt_folders_file <- strsplit(st_example, .Platform$file.sep)[[1]]
# Keep the last N layers
it_folders_names_to_keep = 2
snm_file_name <- tail(strsplit(st_example, "/")[[1]],n=1)
ls_srt_folders_keep <- head(tail(ls_srt_folders_file, it_folders_names_to_keep+1),
                            it_folders_names_to_keep)
# Show folder names
print(paste0('snm_file_name:', snm_file_name))
print(paste0('last ', it_folders_names_to_keep, ' folders:'))
print(ls_srt_folders_keep)


## ------------------------------------------------------------------------------------------------------
# inputs
it_folders_names_to_keep = 2
spn_example <- 'C:/Users/fan/R4Econ/amto/tibble/fs_tib_basics.Rmd'
# copy these
ls_srt_folders_name_keep <- tail(strsplit(st_example, "/")[[1]], n=it_folders_names_to_keep+1)
snm_file_name <- tail(ls_srt_folders_name_keep, 1)
ls_srt_folders_keep <- head(ls_srt_folders_name_keep, it_folders_names_to_keep)
# print
print(paste0('snm_file_name:', snm_file_name))
print(paste0('last ', it_folders_names_to_keep, ' folders:'))
print(ls_srt_folders_keep)

