---
title: "R Generate and Combine Fixed and Random Matrix"
author: Fan Wang
output:
  pdf_document: default
  html_notebook:
    number_sections: yes
  html_document:
    df_print: paged
---

Go back to [fan](http://fanwangecon.github.io/)'s [REconTools](https://fanwangecon.github.io/REconTools/) Package, [R4Econ](https://fanwangecon.github.io/R4Econ/) Repository, or [Intro Stats with R](https://fanwangecon.github.io/Stat4Econ/) Repository.

```{r GlobalOptions, echo = T, results = 'hide', message=F, warning=F}
options(knitr.duplicate.label = 'allow')
```
```{r loadlib, echo = T, results = 'hide', message=F, warning=F}
library(tidyverse)
library(knitr)
library(kableExtra)
# file name
st_file_name = 'fs_genmatrix'
# Generate R File
try(purl(paste0(st_file_name, ".Rmd"), output=paste0(st_file_name, ".R"), documentation = 2))
# Generate PDF and HTML
# rmarkdown::render("C:/Users/fan/R4Econ/support/matrix/fs_genmatrix.Rmd", "pdf_document")
# rmarkdown::render("C:/Users/fan/R4Econ/support/matrix/fs_genmatrix.Rmd", "html_document")
```

## Generate Matrixes

### Create a N by 2 Matrix from 3 arrays

Names of each array become row names automatically.

```{r fixed matrix}
ar_row_one <- c(-1,+1)
ar_row_two <- c(-3,-2)
ar_row_three <- c(0.35,0.75)

mt_n_by_2 <- rbind(ar_row_one, ar_row_two, ar_row_three)
kable(mt_n_by_2) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "responsive"))
```

### Generate Random Matrixes

Random draw from the normal distribution, random draw from the uniform distribution, and combine resulting matrixes.

```{r random matrix}
# Generate 15 random normal, put in 5 rows, and 3 columns
mt_rnorm <- matrix(rnorm(15,mean=0,sd=1), nrow=5, ncol=3)

# Generate 15 random normal, put in 5 rows, and 3 columns
mt_runif <- matrix(runif(15,min=0,max=1), nrow=5, ncol=5)

# Combine
mt_rnorm_runif <- cbind(mt_rnorm, mt_runif)

# Display
kable(mt_rnorm_runif) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "responsive"))
```
