---
title: "CES log lin formulas working with micro estimates"
output:
  html_document:
    df_print: paged
    number_sections: true
    toc: true
    toc_depth: 3
  html_notebook:
    number_sections: true
  word_document:
    number_sections: true
  pdf_document:
    number_sections: true
    toc: true
    toc_depth: 3
urlcolor: blue
---

Back to **[Fan](https://fanwangecon.github.io/)**'s R4Econ Homepage **[Table of Content](https://fanwangecon.github.io/R4Econ/)**

# Outline

In this file, we solve a linear spline inversion problem that is required for solving the inequality constrained planner optimization problem given CRS CES or linear one input production function.

1. **G1**: Provide parameters and draw four linear lines, where 1 line's y-intercept is positive, 2 lines' y-intercepts are negative, 1 line's y-intercept is 0. All lines are linear. One of the line with negative y-intercept has the same slope as the origin line. Slopes are all monotonically increasing. Draw random parameters in fact. Allow for more than 4 lines, many many lines possibly.
2. **G2**: Find, Mark out on graph the x-intercepts.
3. **G3**: Draw the unconstrained sum of the lines
4. **G4**: Draw the constrained sum of the lines, where by constraint we mean only the parts of the lines where y(x)>0
    - figure could be presented as summed area plot
5. **G5**: Solve for and identify the y values corresponding to x-intercept for the linear summed spline
6. **G6**: Invert the figure

*Function parameter features*

- So there are 6 figures, this should be written as a function so that arbitrarily more positive and negative sloped lines could be added. Should also be possible to have identical lines.
